/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Evaluate */
        post: operations["evaluate_api_v1_evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simplify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simplify */
        post: operations["simplify_api_v1_simplify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/expand": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Expand */
        post: operations["expand_api_v1_expand_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/factor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Factor */
        post: operations["factor_api_v1_factor_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/solve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Solve */
        post: operations["solve_api_v1_solve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/derivative": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Derivative */
        post: operations["derivative_api_v1_derivative_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integral": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Integral */
        post: operations["integral_api_v1_integral_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matrix/operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Matrix Operations */
        post: operations["matrix_operations_api_v1_matrix_operations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matrix/ref": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Matrix Ref
         * @description Fase C (spec UX estilo ClassCalc, sección 4).
         */
        post: operations["matrix_ref_api_v1_matrix_ref_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matrix/rref": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Matrix Rref
         * @description Fase C (spec UX estilo ClassCalc, sección 4).
         */
        post: operations["matrix_rref_api_v1_matrix_rref_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matrix/determinant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Matrix Determinant */
        post: operations["matrix_determinant_api_v1_matrix_determinant_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matrix/inverse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Matrix Inverse */
        post: operations["matrix_inverse_api_v1_matrix_inverse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matrix/transpose": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Matrix Transpose */
        post: operations["matrix_transpose_api_v1_matrix_transpose_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matrix/power": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Matrix Power */
        post: operations["matrix_power_api_v1_matrix_power_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matrix/norm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Matrix Norm
         * @description P5 (spec v2 §6) — mismo patrón que /matrix/determinant: escalar,
         *     no matriz, con result_approx además de la forma exacta.
         */
        post: operations["matrix_norm_api_v1_matrix_norm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matrix/trace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Matrix Trace
         * @description Módulo L0 (spec_graficacion_matrices_estadistica_unidades.md,
         *     sección 5) — mismo patrón que /matrix/norm: escalar de una sola
         *     matriz.
         */
        post: operations["matrix_trace_api_v1_matrix_trace_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matrix/rank": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Matrix Rank
         * @description Módulo L0 — rango expuesto como operación con resultado visible;
         *     reutiliza Matrix.rank() de SymPy (el mismo cálculo interno de la
         *     clasificación de sistemas de Fase B, sin tocar esa lógica ni
         *     duplicarla).
         */
        post: operations["matrix_rank_api_v1_matrix_rank_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/matrix/eigen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Matrix Eigen
         * @description Fase 2 — passthrough trivial real (sección 2).
         */
        post: operations["matrix_eigen_api_v1_matrix_eigen_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graph/2d": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Graph 2D */
        post: operations["graph_2d_api_v1_graph_2d_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/limit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Limit */
        post: operations["limit_api_v1_limit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Series */
        post: operations["series_api_v1_series_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/solve/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Solve System
         * @description Passthrough real (dejó de ser stub): sistemas lineales vía
         *     `sympy.linsolve`, no lineales vía `sympy.solve` — ver
         *     `phase2_service.compute_solve_system`.
         */
        post: operations["solve_system_api_v1_solve_system_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inequality": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inequality */
        post: operations["inequality_api_v1_inequality_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inequality/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Inequality System
         * @description Pendiente #5 (revisión post-Módulo D, pedido por el usuario):
         *     sistema de inecuaciones lineales — equivalente Full/SymPy del ya
         *     construido en Lite (linearInequalitySystem.ts). Cada inecuación se
         *     parsea con la misma infraestructura de seguridad que `/inequality`
         *     (parse_inequality_tree, etapas 1-9); la validación de linealidad y de
         *     cantidad exacta de variables vive en linear_inequality_system.py.
         */
        post: operations["inequality_system_api_v1_inequality_system_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integral/improper": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Integral Improper */
        post: operations["integral_improper_api_v1_integral_improper_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graph/3d": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Graph 3D */
        post: operations["graph_3d_api_v1_graph_3d_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graph/parametric": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Graph Parametric */
        post: operations["graph_parametric_api_v1_graph_parametric_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/graph/polar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Graph Polar */
        post: operations["graph_polar_api_v1_graph_polar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/derivative/partial": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Derivative Partial */
        post: operations["derivative_partial_api_v1_derivative_partial_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/derivative/implicit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Derivative Implicit */
        post: operations["derivative_implicit_api_v1_derivative_implicit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/statistics/descriptive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Statistics Descriptive */
        post: operations["statistics_descriptive_api_v1_statistics_descriptive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/statistics/correlation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Statistics Correlation
         * @description Módulo M1 (spec_graficacion_matrices_estadistica_unidades.md,
         *     sección 6.2).
         */
        post: operations["statistics_correlation_api_v1_statistics_correlation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/statistics/combinatorics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Statistics Combinatorics */
        post: operations["statistics_combinatorics_api_v1_statistics_combinatorics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/statistics/binomial": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Statistics Binomial */
        post: operations["statistics_binomial_api_v1_statistics_binomial_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/statistics/normal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Statistics Normal */
        post: operations["statistics_normal_api_v1_statistics_normal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/statistics/poisson": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Statistics Poisson
         * @description Módulo N0 (spec_graficacion_matrices_estadistica_unidades.md, sección 7).
         */
        post: operations["statistics_poisson_api_v1_statistics_poisson_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/statistics/uniform": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Statistics Uniform */
        post: operations["statistics_uniform_api_v1_statistics_uniform_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/statistics/exponential": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Statistics Exponential */
        post: operations["statistics_exponential_api_v1_statistics_exponential_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BinomialRequest */
        BinomialRequest: {
            /** N */
            n: number;
            /** P */
            p: number;
            /**
             * K
             * @default 0
             */
            k: number;
            /**
             * Query
             * @enum {string}
             */
            query: "pmf" | "cdf" | "survival" | "mean" | "variance";
        };
        /** CombinatoricsRequest */
        CombinatoricsRequest: {
            /** N */
            n: number;
            /**
             * R
             * @default 0
             */
            r: number;
            /**
             * Fn
             * @enum {string}
             */
            fn: "nCr" | "nPr" | "factorial";
        };
        /** DerivativeRequest */
        DerivativeRequest: {
            /** Expression */
            expression: string;
            /**
             * Variable
             * @default x
             */
            variable: string;
            /**
             * Order
             * @default 1
             */
            order: number;
        };
        /** EquationSolution */
        EquationSolution: {
            /** Text */
            text: string;
            /** Latex */
            latex: string;
            /**
             * Is Complex
             * @default false
             */
            is_complex: boolean;
        };
        /** DomainCondition */
        DomainCondition: {
            /** Text */
            text: string;
            /** Latex */
            latex: string;
            /** Variable */
            variable?: string | null;
            /**
             * Kind
             * @default domain
             */
            kind: string;
        };
        /**
         * ErrorCode
         * @description Enum central — el backend NUNCA usa un string de error fuera de esta lista.
         *
         *     Mapeo error_code -> status HTTP -> disparador (spec, sección 4):
         *       PARSE_ERROR            200  entrada no parseable / insegura
         *       VALIDATION_ERROR       422  payload Pydantic inválido
         *       TIMEOUT                200  operación (o verificación de pasos) excede su presupuesto
         *       COMPLEXITY_LIMIT       200  nodos/profundidad/dígitos/exponente/términos excedidos
         *       SINGULAR_MATRIX        200  inversa de matriz singular
         *       DIMENSION_MISMATCH     200  matriz no cuadrada/rectangular/incompatible
         *       DOMAIN_ERROR           200  operación matemáticamente indefinida
         *       AMBIGUOUS_VARIABLE     200  solve con >1 símbolo libre sin variable especificada
         *       INVALID_VARIABLE       200  variable de gráfica no coincide con la expresión
         *       UNSUPPORTED_IN_PHASE_1 200  feature de Fase 2 sin passthrough trivial
         *       INTERNAL_ERROR         500  excepción no esperada / error de red en el cliente
         * @enum {string}
         */
        ErrorCode: "PARSE_ERROR" | "VALIDATION_ERROR" | "TIMEOUT" | "COMPLEXITY_LIMIT" | "SINGULAR_MATRIX" | "DIMENSION_MISMATCH" | "DOMAIN_ERROR" | "AMBIGUOUS_VARIABLE" | "INVALID_VARIABLE" | "UNSUPPORTED_IN_PHASE_1" | "UNSUPPORTED_OPERATION" | "INTERNAL_ERROR";
        /** EvaluateRequest */
        EvaluateRequest: {
            /** Expression */
            expression: string;
            /**
             * Angle Unit
             * @default rad
             * @enum {string}
             */
            angle_unit: "rad" | "deg";
            /** Substitutions */
            substitutions?: {
                [key: string]: string;
            } | null;
        };
        /** ExponentialRequest */
        ExponentialRequest: {
            /**
             * Lam
             * @default 1
             */
            lam: number;
            /**
             * X
             * @default 0
             */
            x: number;
            /**
             * Query
             * @enum {string}
             */
            query: "cdf" | "mean" | "variance";
        };
        /** ExpressionRequest */
        ExpressionRequest: {
            /** Expression */
            expression: string;
        };
        /** Graph2DRequest */
        Graph2DRequest: {
            /** Expressions */
            expressions: string[];
            /**
             * Variable
             * @default x
             */
            variable: string;
            /** X Min */
            x_min?: number | null;
            /** X Max */
            x_max?: number | null;
            /** Samples */
            samples?: number | null;
            /**
             * Angle Unit
             * @default rad
             * @enum {string}
             */
            angle_unit: "rad" | "deg";
        };
        /** Graph3DRequest */
        Graph3DRequest: {
            /** Expression */
            expression: string;
            /** Variables */
            variables?: string[];
            /** X Range */
            x_range?: number[];
            /** Y Range */
            y_range?: number[];
        };
        /**
         * GraphAnalysis
         * @description Análisis simbólico best-effort de una expresión graficada (dominio,
         *     rango, interceptos, extremos locales, inflexión). Cada campo puede
         *     quedar en `None`/`[]` si SymPy no pudo resolverlo dentro del
         *     presupuesto de tiempo (ver `graph_service._run_with_timeout`) o si no
         *     hay un método simbólico aplicable — nunca bloquea la graficación
         *     numérica en sí, que sigue funcionando igual sin importar esto.
         */
        GraphAnalysis: {
            /** Domain Text */
            domain_text?: string | null;
            /** Domain Latex */
            domain_latex?: string | null;
            /** Range Text */
            range_text?: string | null;
            /** Range Latex */
            range_latex?: string | null;
            /** Y Intercept */
            y_intercept?: string | null;
            /**
             * X Intercepts
             * @default []
             */
            x_intercepts: string[];
            /**
             * Local Maxima
             * @default []
             */
            local_maxima: string[];
            /**
             * Local Minima
             * @default []
             */
            local_minima: string[];
            /**
             * Inflection Points
             * @default []
             */
            inflection_points: string[];
        };
        /** GraphData */
        GraphData: {
            /** Traces */
            traces: components["schemas"]["Trace"][];
            /** X Range */
            x_range: number[];
            /** Y Range */
            y_range?: number[] | null;
            /**
             * Points Truncated
             * @default false
             */
            points_truncated: boolean;
            /** Analysis */
            analysis?: components["schemas"]["GraphAnalysis"][] | null;
            /** X Axis Label (Fase F, Módulo F3 -- parche manual, ver cabecera del archivo) */
            x_axis_label?: string | null;
            /** Y Axis Label (Fase F, Módulo F3 -- parche manual, ver cabecera del archivo) */
            y_axis_label?: string | null;
        };
        /** GraphParametricRequest */
        GraphParametricRequest: {
            /** X Expression */
            x_expression: string;
            /** Y Expression */
            y_expression: string;
            /**
             * Parameter
             * @default t
             */
            parameter: string;
            /**
             * T Min
             * @default 0
             */
            t_min: number;
            /**
             * T Max
             * @default 6.283185307179586
             */
            t_max: number;
        };
        /**
         * GraphPolarRequest
         * @description Módulo I0 (Fase I): gráfica polar r=f(θ). Mismo patrón de campos
         *     que GraphParametricRequest — rango de θ expuesto y editable, con el
         *     mismo default de una vuelta completa (DEDUCIBLE, sección 2 del spec:
         *     "mismo patrón que el rango de t ya usado en paramétricas").
         */
        GraphPolarRequest: {
            /** R Expression */
            r_expression: string;
            /**
             * Variable
             * @default theta
             */
            variable: string;
            /**
             * Theta Min
             * @default 0
             */
            theta_min: number;
            /**
             * Theta Max
             * @default 6.283185307179586
             */
            theta_max: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImplicitDerivativeRequest */
        ImplicitDerivativeRequest: {
            /** Equation */
            equation: string;
            /**
             * Dependent Variable
             * @default y
             */
            dependent_variable: string;
            /**
             * Independent Variable
             * @default x
             */
            independent_variable: string;
        };
        /** ImproperIntegralRequest */
        ImproperIntegralRequest: {
            /** Expression */
            expression: string;
            /**
             * Variable
             * @default x
             */
            variable: string;
            /** Lower Bound */
            lower_bound: string;
            /** Upper Bound */
            upper_bound: string;
        };
        /** InequalityRequest */
        InequalityRequest: {
            /** Inequality */
            inequality: string;
            /** Variable */
            variable?: string | null;
        };
        /**
         * InequalitySystemRequest
         * @description Pendiente #5 (revisión de pendientes del track de teclado/motor,
         *     pedido por el usuario): sistema de inecuaciones lineales — equivalente
         *     Full/SymPy de linearInequalitySystem.ts (Lite). Alcance confirmado:
         *     exactamente 2 variables (la validación de cantidad exacta vive en el
         *     servicio, no acá, para dar un mensaje más claro que un 422 genérico).
         */
        InequalitySystemRequest: {
            /** Inequalities */
            inequalities: string[];
            /** Variables */
            variables: string[];
        };
        /** IntegralRequest */
        IntegralRequest: {
            /** Expression */
            expression: string;
            /**
             * Variable
             * @default x
             */
            variable: string;
            /** Lower Bound */
            lower_bound?: string | null;
            /** Upper Bound */
            upper_bound?: string | null;
        };
        /** LimitRequest */
        LimitRequest: {
            /** Expression */
            expression: string;
            /**
             * Variable
             * @default x
             */
            variable: string;
            /**
             * Point
             * @default 0
             */
            point: string;
            /**
             * Direction
             * @default both
             * @enum {string}
             */
            direction: "both" | "left" | "right";
        };
        /** MathResponse */
        MathResponse: {
            /** Success */
            success: boolean;
            operation: components["schemas"]["OperationType"];
            /** Request Id */
            request_id: string;
            result_kind?: components["schemas"]["ResultKind"] | null;
            /**
             * Result Views
             * @default []
             */
            result_views?: components["schemas"]["ResultView"][];
            result_type?: components["schemas"]["ResultType"] | null;
            /** Input Text */
            input_text?: string | null;
            /** Input Latex */
            input_latex?: string | null;
            /** Result Latex */
            result_latex?: string | null;
            /** Result Text */
            result_text?: string | null;
            /** Result Approx */
            result_approx?: number | null;
            /** Result Data */
            result_data?: components["schemas"]["EquationSolution"][] | string[][] | null;
            /**
             * Steps
             * @default []
             */
            steps: components["schemas"]["Step"][];
            /** Has Detailed Steps */
            has_detailed_steps: boolean;
            graph_data?: components["schemas"]["GraphData"] | null;
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
            /**
             * Domain Conditions
             * @default []
             */
            domain_conditions?: components["schemas"]["DomainCondition"][];
            error_code?: components["schemas"]["ErrorCode"] | null;
            /** Error Message */
            error_message?: string | null;
            /** Duration Ms */
            duration_ms: number;
        };
        /** MatrixEigenRequest */
        MatrixEigenRequest: {
            /** Matrix */
            matrix: string[][];
        };
        /**
         * MatrixOpKind
         * @enum {string}
         */
        MatrixOpKind: "add" | "subtract" | "multiply" | "kronecker" | "dot" | "cross";
        /** MatrixOperationRequest */
        MatrixOperationRequest: {
            operation: components["schemas"]["MatrixOpKind"];
            /** Matrix A */
            matrix_a: string[][];
            /** Matrix B */
            matrix_b: string[][];
        };
        /** MatrixPowerRequest */
        MatrixPowerRequest: {
            /** Matrix */
            matrix: string[][];
            /** Exponent */
            exponent: number;
        };
        /** MatrixSingleRequest */
        MatrixSingleRequest: {
            /** Matrix */
            matrix: string[][];
        };
        /** NormalRequest */
        NormalRequest: {
            /**
             * Mu
             * @default 0
             */
            mu: number;
            /**
             * Sigma
             * @default 1
             */
            sigma: number;
            /**
             * X
             * @default 0
             */
            x: number;
            /**
             * A
             * @default 0
             */
            a: number;
            /**
             * B
             * @default 0
             */
            b: number;
            /**
             * Query
             * @enum {string}
             */
            query: "cdf" | "range" | "zscore";
        };
        /**
         * OperationType
         * @enum {string}
         */
        OperationType: "evaluate" | "simplify" | "factor" | "expand" | "solve" | "derivative" | "integral" | "matrix_operation" | "matrix_determinant" | "matrix_inverse" | "graph_2d" | "solve_system" | "inequality" | "limit" | "series" | "matrix_eigen" | "integral_improper" | "graph_3d" | "graph_parametric" | "derivative_partial" | "derivative_implicit" | "matrix_transpose" | "matrix_power" | "matrix_ref" | "matrix_rref" | "matrix_norm" | "matrix_trace" | "matrix_rank" | "statistics_correlation" | "statistics_descriptive" | "statistics_combinatorics" | "statistics_binomial" | "statistics_normal" | "statistics_poisson" | "statistics_uniform" | "statistics_exponential" | "inequality_system" | "graph_polar" | "ode" | "complex_residue" | "complex_singularities";
        /** PartialDerivativeRequest */
        PartialDerivativeRequest: {
            /** Expression */
            expression: string;
            /** Variable */
            variable: string;
            /**
             * Order
             * @default 1
             */
            order: number;
        };
        /** PoissonRequest */
        PoissonRequest: {
            /**
             * Lam
             * @default 1
             */
            lam: number;
            /**
             * K
             * @default 0
             */
            k: number;
            /**
             * Query
             * @enum {string}
             */
            query: "pmf" | "cdf" | "mean" | "variance";
        };
        /**
         * ResultKind
         * @enum {string}
         */
        ResultKind: "numeric" | "algebraic" | "rational" | "radical" | "logarithmic" | "exponential" | "trigonometric" | "complex" | "equation" | "inequality" | "calculus" | "matrix" | "graph" | "other";
        /** ResultView */
        ResultView: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Latex */
            latex: string;
            kind: components["schemas"]["ResultKind"];
        };
        /**
         * ResultType
         * @enum {string}
         */
        ResultType: "scalar" | "equation_solutions" | "matrix" | "boolean" | "graph" | "identity" | "contradiction" | "inequality_region" | "ode_solution" | "complex_residue" | "complex_singularities";
        /** SeriesRequest */
        SeriesRequest: {
            /** Expression */
            expression: string;
            /**
             * Variable
             * @default x
             */
            variable: string;
            /**
             * Point
             * @default 0
             */
            point: string;
            /**
             * Order
             * @default 6
             */
            order: number;
        };
        /** SolveRequest */
        SolveRequest: {
            /** Equation */
            equation: string;
            /** Variable */
            variable?: string | null;
            /**
             * Angle Unit
             * @default rad
             * @enum {string}
             */
            angle_unit: "rad" | "deg";
        };
        /** SolveSystemRequest */
        SolveSystemRequest: {
            /** Equations */
            equations: string[];
            /** Variables */
            variables: string[];
        };
        /**
         * StatisticsCorrelationRequest
         * @description Módulo M1 (spec_graficacion_matrices_estadistica_unidades.md,
         *     sección 6.2): pares (x,y), no una sola lista — request separado de
         *     StatisticsDescriptiveRequest en vez de forzarlo en el mismo schema.
         */
        StatisticsCorrelationRequest: {
            /** X */
            x: number[];
            /** Y */
            y: number[];
            /**
             * Query
             * @enum {string}
             */
            query: "correlation" | "slope" | "intercept";
        };
        /** StatisticsDescriptiveRequest */
        StatisticsDescriptiveRequest: {
            /** Values */
            values: number[];
            /**
             * Stat
             * @enum {string}
             */
            stat: "mean" | "median" | "mode" | "sum" | "sumsq" | "n" | "min" | "max" | "range" | "mad" | "variance" | "stdev" | "q1" | "q2" | "q3" | "iqr" | "percentile";
            /**
             * Variance Kind
             * @default population
             * @enum {string}
             */
            variance_kind: "population" | "sample";
            /** Percentile P */
            percentile_p?: number | null;
        };
        /** Step */
        Step: {
            /** Index */
            index: number;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Rule */
            rule?: string | null;
            /** Latex Before */
            latex_before: string;
            /** Latex After */
            latex_after: string;
        };
        /** Trace */
        Trace: {
            /** Type */
            type: string;
            /** Name */
            name: string;
            /** X */
            x: number[];
            /** Y */
            y: (number | null)[];
            /** Z */
            z?: number[][] | null;
            /**
             * Hole X
             * @default []
             */
            hole_x?: number[];
            /**
             * Hole Y
             * @default []
             */
            hole_y?: number[];
        };
        /** UniformRequest */
        UniformRequest: {
            /**
             * A
             * @default 0
             */
            a: number;
            /**
             * B
             * @default 1
             */
            b: number;
            /**
             * X
             * @default 0
             */
            x: number;
            /**
             * Query
             * @enum {string}
             */
            query: "cdf" | "mean" | "variance";
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    evaluate_api_v1_evaluate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simplify_api_v1_simplify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpressionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    expand_api_v1_expand_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpressionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    factor_api_v1_factor_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExpressionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    solve_api_v1_solve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    derivative_api_v1_derivative_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DerivativeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    integral_api_v1_integral_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntegralRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    matrix_operations_api_v1_matrix_operations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatrixOperationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    matrix_ref_api_v1_matrix_ref_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatrixSingleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    matrix_rref_api_v1_matrix_rref_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatrixSingleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    matrix_determinant_api_v1_matrix_determinant_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatrixSingleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    matrix_inverse_api_v1_matrix_inverse_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatrixSingleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    matrix_transpose_api_v1_matrix_transpose_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatrixSingleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    matrix_power_api_v1_matrix_power_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatrixPowerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    matrix_norm_api_v1_matrix_norm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatrixSingleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    matrix_trace_api_v1_matrix_trace_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatrixSingleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    matrix_rank_api_v1_matrix_rank_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatrixSingleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    matrix_eigen_api_v1_matrix_eigen_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MatrixEigenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    graph_2d_api_v1_graph_2d_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Graph2DRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    limit_api_v1_limit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LimitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    series_api_v1_series_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeriesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    solve_system_api_v1_solve_system_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolveSystemRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inequality_api_v1_inequality_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InequalityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inequality_system_api_v1_inequality_system_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InequalitySystemRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    integral_improper_api_v1_integral_improper_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImproperIntegralRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    graph_3d_api_v1_graph_3d_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Graph3DRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    graph_parametric_api_v1_graph_parametric_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GraphParametricRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    graph_polar_api_v1_graph_polar_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GraphPolarRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    derivative_partial_api_v1_derivative_partial_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PartialDerivativeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    derivative_implicit_api_v1_derivative_implicit_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImplicitDerivativeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    statistics_descriptive_api_v1_statistics_descriptive_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatisticsDescriptiveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    statistics_correlation_api_v1_statistics_correlation_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatisticsCorrelationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    statistics_combinatorics_api_v1_statistics_combinatorics_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CombinatoricsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    statistics_binomial_api_v1_statistics_binomial_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BinomialRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    statistics_normal_api_v1_statistics_normal_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NormalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    statistics_poisson_api_v1_statistics_poisson_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PoissonRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    statistics_uniform_api_v1_statistics_uniform_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UniformRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    statistics_exponential_api_v1_statistics_exponential_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExponentialRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
